try to use shoulda, but these some bugs:
Randomized with seed 8953
...F..

Failures:

  1) Video 
     Failure/Error: it { should belongs_to(:category) }
     NoMethodError:
       undefined method `belongs_to' for #<RSpec::ExampleGroups::Video:0x007f7fd1e534b0>
     # ./spec/models/video_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.07004 seconds (files took 2.43 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/models/video_spec.rb:6 # Video 

Randomized with seed 8953